language:
  - java 

jdk:
  - oraclejdk8

env:
  global:
    - DITAOT="3.1.2"
    - URL="https://github.com/dita-ot/dita-ot/releases/download/$DITAOT/dita-ot-$DITAOT.zip"

before_script:
  - zip -qr org.doctales.reveal.zip . -x *.zip* *.git/* *temp/* *out/*
  - curl -LO $URL
  - unzip -q dita-ot-$DITAOT.zip
  - chmod +x dita-ot-$DITAOT/bin/dita
  - chmod +x dita-ot-$DITAOT/bin/ant
  - dita-ot-$DITAOT/bin/dita --install org.doctales.reveal.zip
  - BASEDIR=$(dirname "$0")

script:
  - dita-ot-$DITAOT/bin/dita -i samples/sample.ditamap -f pdf2 -v -Dschematron.topic.validation.files=../rules/topic-validation.sch,../rules/topic-terminology.sch -Dschematron.fail=false -Dschematron.failon.fatal=true -Dschematron.failon.error=true -Dschematron.failon.warning=false -Dschematron.failon.info=false

notifications:
  slack:
    rooms:
      - doctales:BkI4k7awSFS5X5aT04Y3vHQ9#reveal
