name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
env:
  DITA_OT_VERSION: 4.1.2

jobs:

  dita-ot_4-1-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: DITA-OT
        run: |
          curl --location --remote-name https://github.com/dita-ot/dita-ot/releases/download/4.1.2/dita-ot-4.1.2.zip
          unzip dita-ot-4.1.2
          chmod +x dita-ot-4.1.2/bin/dita
          chmod +x dita-ot-4.1.2/bin/ant
          zip -qq -r org.jung.reveal.zip . -x ./.git/**\*
          dita-ot-4.1.2/bin/dita install org.jung.reveal.zip --force
      - name: Build test files
        run: dita-ot-4.1.2/bin/dita --project=samples/sample.xml --output=4.1.2 --processing-mode=strict --verbose
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: org.jung.reveal-4-1-2
          path: |
            4.1.2

  dita-ot_4-0-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: DITA-OT
        run: |
          curl --location --remote-name https://github.com/dita-ot/dita-ot/releases/download/4.0.2/dita-ot-4.0.2.zip
          unzip dita-ot-4.0.2
          chmod +x dita-ot-4.0.2/bin/dita
          chmod +x dita-ot-4.0.2/bin/ant
          zip -qq -r org.jung.reveal.zip . -x ./.git/**\*
          dita-ot-4.0.2/bin/dita install org.jung.reveal.zip --force
      - name: Build test files
        run: dita-ot-4.0.2/bin/dita --project=samples/sample.xml --output=4.0.2 --processing-mode=strict --verbose
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: org.jung.reveal-4-0-2
          path: |
            4.0.2

  dita-ot_3-7-4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: DITA-OT
        run: |
          curl --location --remote-name https://github.com/dita-ot/dita-ot/releases/download/3.7.4/dita-ot-3.7.4.zip
          unzip dita-ot-3.7.4
          chmod +x dita-ot-3.7.4/bin/dita
          chmod +x dita-ot-3.7.4/bin/ant
          zip -qq -r org.jung.reveal.zip . -x ./.git/**\*
          dita-ot-3.7.4/bin/dita install org.jung.reveal.zip --force
      - name: Build test files
        run: dita-ot-3.7.4/bin/dita --project=samples/sample.xml --output=3.7.4 --processing-mode=strict --verbose
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: org.jung.reveal-3-7-4
          path: |
            3.7.4
